/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace std_msgs
{
    public sealed class Float64 : LCM.LCM.LCMEncodable
    {
        public double data;
 
        public Float64()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x90eea081d4d0b10aL;
 
        static Float64()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("std_msgs.Float64"))
                return 0L;
 
            classes.Add("std_msgs.Float64");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.data); 
 
        }
 
        public Float64(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Float64(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static std_msgs.Float64 _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            std_msgs.Float64 o = new std_msgs.Float64();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.data = ins.ReadDouble();
 
        }
 
        public std_msgs.Float64 Copy()
        {
            std_msgs.Float64 outobj = new std_msgs.Float64();
            outobj.data = this.data;
 
            return outobj;
        }
    }
}

