/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace std_msgs
{
    public sealed class Int32 : LCM.LCM.LCMEncodable
    {
        public int data;
 
        public Int32()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x165e7cfbf548811fL;
 
        static Int32()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("std_msgs.Int32"))
                return 0L;
 
            classes.Add("std_msgs.Int32");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.data); 
 
        }
 
        public Int32(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Int32(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static std_msgs.Int32 _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            std_msgs.Int32 o = new std_msgs.Int32();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.data = ins.ReadInt32();
 
        }
 
        public std_msgs.Int32 Copy()
        {
            std_msgs.Int32 outobj = new std_msgs.Int32();
            outobj.data = this.data;
 
            return outobj;
        }
    }
}

