/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class Point_List : LCM.LCM.LCMEncodable
    {
        public int n;
        public geometry_msgs.Point[] data;
 
        public Point_List()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x89a7b2e33a5ee21cL;
 
        static Point_List()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.Point_List"))
                return 0L;
 
            classes.Add("geometry_msgs.Point_List");
            ulong hash = LCM_FINGERPRINT_BASE
                 + geometry_msgs.Point._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.n); 
 
            for (int a = 0; a < this.n; a++) {
                this.data[a]._encodeRecursive(outs); 
            }
 
        }
 
        public Point_List(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Point_List(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.Point_List _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.Point_List o = new geometry_msgs.Point_List();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.n = ins.ReadInt32();
 
            this.data = new geometry_msgs.Point[(int) n];
            for (int a = 0; a < this.n; a++) {
                this.data[a] = geometry_msgs.Point._decodeRecursiveFactory(ins);
            }
 
        }
 
        public geometry_msgs.Point_List Copy()
        {
            geometry_msgs.Point_List outobj = new geometry_msgs.Point_List();
            outobj.n = this.n;
 
            outobj.data = new geometry_msgs.Point[(int) n];
            for (int a = 0; a < this.n; a++) {
                outobj.data[a] = this.data[a].Copy();
            }
 
            return outobj;
        }
    }
}

