/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class TransformNewStamp : LCM.LCM.LCMEncodable
    {
        public double timestamp;
        public geometry_msgs.Vector3 translation;
        public geometry_msgs.Quaternion rotation;
 
        public TransformNewStamp()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xf8830c4aec4b5864L;
 
        static TransformNewStamp()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.TransformNewStamp"))
                return 0L;
 
            classes.Add("geometry_msgs.TransformNewStamp");
            ulong hash = LCM_FINGERPRINT_BASE
                 + geometry_msgs.Vector3._hashRecursive(classes)
                 + geometry_msgs.Quaternion._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.timestamp); 
 
            this.translation._encodeRecursive(outs); 
 
            this.rotation._encodeRecursive(outs); 
 
        }
 
        public TransformNewStamp(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public TransformNewStamp(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.TransformNewStamp _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.TransformNewStamp o = new geometry_msgs.TransformNewStamp();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.timestamp = ins.ReadDouble();
 
            this.translation = geometry_msgs.Vector3._decodeRecursiveFactory(ins);
 
            this.rotation = geometry_msgs.Quaternion._decodeRecursiveFactory(ins);
 
        }
 
        public geometry_msgs.TransformNewStamp Copy()
        {
            geometry_msgs.TransformNewStamp outobj = new geometry_msgs.TransformNewStamp();
            outobj.timestamp = this.timestamp;
 
            outobj.translation = this.translation.Copy();
 
            outobj.rotation = this.rotation.Copy();
 
            return outobj;
        }
    }
}

