mission_point:
- {x: 0.0,y: 0.0,z: 2.0,yaw: 0.0}
- {x: 0.0,y: 1.0,z: 2.0,yaw: 0.0}
- {x: 0.0,y: 2.0,z: 2.0,yaw: 0.0}
- {x: 0.0,y: 3.0,z: 2.0,yaw: 0.0}
- {x: 0.0,y: 4.0,z: 2.0,yaw: 0.0}
- {x: 0.0,y: 5.0,z: 2.0,yaw: 0.0}
- {x: 0.0,y: 6.0,z: 2.0,yaw: 0.0}
- {x: 0.0,y: 7.0,z: 2.0,yaw: 0.0}
- {x: 0.0,y: 8.0,z: 2.0,yaw: 0.0}
- {x: 0.0,y: 9.0,z: 2.0,yaw: 0.0}
- {x: 0.0,y: 10.0,z: 2.0,yaw: 0.0}
- {x: 1.0,y: 10.0,z: 2.0,yaw: 0.0}
- {x: 2.0,y: 10.0,z: 2.0,yaw: 0.0}
- {x: 3.0,y: 10.0,z: 2.0,yaw: 0.0}
- {x: 4.0,y: 10.0,z: 2.0,yaw: 0.0}
- {x: 5.0,y: 10.0,z: 2.0,yaw: 0.0}
- {x: 5.0,y: 9.0,z: 2.0,yaw: 0.0}
- {x: 5.0,y: 8.0,z: 2.0,yaw: 0.0}
- {x: 5.0,y: 7.0,z: 2.0,yaw: 0.0}
- {x: 5.0,y: 6.0,z: 2.0,yaw: 0.0}
- {x: 5.0,y: 5.0,z: 2.0,yaw: 0.0}
- {x: 6.0,y: 5.0,z: 2.0,yaw: 0.0}
- {x: 7.0,y: 5.0,z: 2.0,yaw: 0.0}
- {x: 8.0,y: 5.0,z: 2.0,yaw: 0.0}
- {x: 9.0,y: 5.0,z: 2.0,yaw: 0.0}
- {x: 10.0,y: 5.0,z: 2.0,yaw: 0.0}
- {x: 10.0,y: 4.0,z: 2.0,yaw: 0.0}
- {x: 10.0,y: 3.0,z: 2.0,yaw: 0.0}
- {x: 10.0,y: 2.0,z: 2.0,yaw: 0.0}
- {x: 10.0,y: 1.0,z: 2.0,yaw: 0.0}
- {x: 10.0,y: 0.0,z: 2.0,yaw: 0.0}
- {x: 9.0,y: 0.0,z: 2.0,yaw: 0.0}
- {x: 8.0,y: 0.0,z: 2.0,yaw: 0.0}
- {x: 7.0,y: 0.0,z: 2.0,yaw: 0.0}
- {x: 6.0,y: 0.0,z: 2.0,yaw: 0.0}
- {x: 5.0,y: 0.0,z: 2.0,yaw: 0.0}
- {x: 4.0,y: 0.0,z: 2.0,yaw: 0.0}
- {x: 3.0,y: 0.0,z: 2.0,yaw: 0.0}
- {x: 2.0,y: 0.0,z: 2.0,yaw: 0.0}
- {x: 1.0,y: 0.0,z: 2.0,yaw: 0.0}
- {x: 0.0,y: 0.0,z: 2.0,yaw: 0.0}
- {x: 0.0,y: 0.0,z: 1.0,yaw: 0.0}
- {x: 0.0,y: 0.0,z: 0.0,yaw: 0.0}
- {x: 0.0,y: 0.0,z: -0.5,yaw: 0.0}





