/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class WrenchStamp : LCM.LCM.LCMEncodable
    {
        public double timestamp;
        public geometry_msgs.Vector3 force;
        public geometry_msgs.Vector3 torque;
 
        public WrenchStamp()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x95fb3f62672e5b69L;
 
        static WrenchStamp()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.WrenchStamp"))
                return 0L;
 
            classes.Add("geometry_msgs.WrenchStamp");
            ulong hash = LCM_FINGERPRINT_BASE
                 + geometry_msgs.Vector3._hashRecursive(classes)
                 + geometry_msgs.Vector3._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.timestamp); 
 
            this.force._encodeRecursive(outs); 
 
            this.torque._encodeRecursive(outs); 
 
        }
 
        public WrenchStamp(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public WrenchStamp(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.WrenchStamp _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.WrenchStamp o = new geometry_msgs.WrenchStamp();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.timestamp = ins.ReadDouble();
 
            this.force = geometry_msgs.Vector3._decodeRecursiveFactory(ins);
 
            this.torque = geometry_msgs.Vector3._decodeRecursiveFactory(ins);
 
        }
 
        public geometry_msgs.WrenchStamp Copy()
        {
            geometry_msgs.WrenchStamp outobj = new geometry_msgs.WrenchStamp();
            outobj.timestamp = this.timestamp;
 
            outobj.force = this.force.Copy();
 
            outobj.torque = this.torque.Copy();
 
            return outobj;
        }
    }
}

