/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class Pose : LCM.LCM.LCMEncodable
    {
        public geometry_msgs.Point position;
        public geometry_msgs.Quaternion orientation;
 
        public Pose()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x2d70dd60bd541272L;
 
        static Pose()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.Pose"))
                return 0L;
 
            classes.Add("geometry_msgs.Pose");
            ulong hash = LCM_FINGERPRINT_BASE
                 + geometry_msgs.Point._hashRecursive(classes)
                 + geometry_msgs.Quaternion._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.position._encodeRecursive(outs); 
 
            this.orientation._encodeRecursive(outs); 
 
        }
 
        public Pose(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Pose(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.Pose _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.Pose o = new geometry_msgs.Pose();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.position = geometry_msgs.Point._decodeRecursiveFactory(ins);
 
            this.orientation = geometry_msgs.Quaternion._decodeRecursiveFactory(ins);
 
        }
 
        public geometry_msgs.Pose Copy()
        {
            geometry_msgs.Pose outobj = new geometry_msgs.Pose();
            outobj.position = this.position.Copy();
 
            outobj.orientation = this.orientation.Copy();
 
            return outobj;
        }
    }
}

