/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class QuaternionStamp : LCM.LCM.LCMEncodable
    {
        public double timestamp;
        public double x;
        public double y;
        public double z;
        public double w;
 
        public QuaternionStamp()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x6a36a71b5d7b5447L;
 
        static QuaternionStamp()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.QuaternionStamp"))
                return 0L;
 
            classes.Add("geometry_msgs.QuaternionStamp");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.timestamp); 
 
            outs.Write(this.x); 
 
            outs.Write(this.y); 
 
            outs.Write(this.z); 
 
            outs.Write(this.w); 
 
        }
 
        public QuaternionStamp(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public QuaternionStamp(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.QuaternionStamp _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.QuaternionStamp o = new geometry_msgs.QuaternionStamp();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.timestamp = ins.ReadDouble();
 
            this.x = ins.ReadDouble();
 
            this.y = ins.ReadDouble();
 
            this.z = ins.ReadDouble();
 
            this.w = ins.ReadDouble();
 
        }
 
        public geometry_msgs.QuaternionStamp Copy()
        {
            geometry_msgs.QuaternionStamp outobj = new geometry_msgs.QuaternionStamp();
            outobj.timestamp = this.timestamp;
 
            outobj.x = this.x;
 
            outobj.y = this.y;
 
            outobj.z = this.z;
 
            outobj.w = this.w;
 
            return outobj;
        }
    }
}

