/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class Vector3 : LCM.LCM.LCMEncodable
    {
        public double x;
        public double y;
        public double z;
 
        public Vector3()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x573f2fdd2f76508fL;
 
        static Vector3()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.Vector3"))
                return 0L;
 
            classes.Add("geometry_msgs.Vector3");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.x); 
 
            outs.Write(this.y); 
 
            outs.Write(this.z); 
 
        }
 
        public Vector3(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Vector3(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.Vector3 _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.Vector3 o = new geometry_msgs.Vector3();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.x = ins.ReadDouble();
 
            this.y = ins.ReadDouble();
 
            this.z = ins.ReadDouble();
 
        }
 
        public geometry_msgs.Vector3 Copy()
        {
            geometry_msgs.Vector3 outobj = new geometry_msgs.Vector3();
            outobj.x = this.x;
 
            outobj.y = this.y;
 
            outobj.z = this.z;
 
            return outobj;
        }
    }
}

