/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class WrenchStamp_List : LCM.LCM.LCMEncodable
    {
        public double timestamp;
        public int n;
        public geometry_msgs.Wrench[] data;
 
        public WrenchStamp_List()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xf8c5bccaee56f83eL;
 
        static WrenchStamp_List()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.WrenchStamp_List"))
                return 0L;
 
            classes.Add("geometry_msgs.WrenchStamp_List");
            ulong hash = LCM_FINGERPRINT_BASE
                 + geometry_msgs.Wrench._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.timestamp); 
 
            outs.Write(this.n); 
 
            for (int a = 0; a < this.n; a++) {
                this.data[a]._encodeRecursive(outs); 
            }
 
        }
 
        public WrenchStamp_List(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public WrenchStamp_List(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.WrenchStamp_List _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.WrenchStamp_List o = new geometry_msgs.WrenchStamp_List();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.timestamp = ins.ReadDouble();
 
            this.n = ins.ReadInt32();
 
            this.data = new geometry_msgs.Wrench[(int) n];
            for (int a = 0; a < this.n; a++) {
                this.data[a] = geometry_msgs.Wrench._decodeRecursiveFactory(ins);
            }
 
        }
 
        public geometry_msgs.WrenchStamp_List Copy()
        {
            geometry_msgs.WrenchStamp_List outobj = new geometry_msgs.WrenchStamp_List();
            outobj.timestamp = this.timestamp;
 
            outobj.n = this.n;
 
            outobj.data = new geometry_msgs.Wrench[(int) n];
            for (int a = 0; a < this.n; a++) {
                outobj.data[a] = this.data[a].Copy();
            }
 
            return outobj;
        }
    }
}

