/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace sensor_msgs
{
    public sealed class SITLGps : LCM.LCM.LCMEncodable
    {
        public double time_usec;
        public double latitude_deg;
        public double longitude_deg;
        public double altitude;
        public double eph;
        public double epv;
        public double velocity;
        public double velocity_east;
        public double velocity_north;
        public double velocity_up;
 
        public SITLGps()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x104f4ced1252d9c2L;
 
        static SITLGps()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("sensor_msgs.SITLGps"))
                return 0L;
 
            classes.Add("sensor_msgs.SITLGps");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.time_usec); 
 
            outs.Write(this.latitude_deg); 
 
            outs.Write(this.longitude_deg); 
 
            outs.Write(this.altitude); 
 
            outs.Write(this.eph); 
 
            outs.Write(this.epv); 
 
            outs.Write(this.velocity); 
 
            outs.Write(this.velocity_east); 
 
            outs.Write(this.velocity_north); 
 
            outs.Write(this.velocity_up); 
 
        }
 
        public SITLGps(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public SITLGps(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static sensor_msgs.SITLGps _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            sensor_msgs.SITLGps o = new sensor_msgs.SITLGps();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.time_usec = ins.ReadDouble();
 
            this.latitude_deg = ins.ReadDouble();
 
            this.longitude_deg = ins.ReadDouble();
 
            this.altitude = ins.ReadDouble();
 
            this.eph = ins.ReadDouble();
 
            this.epv = ins.ReadDouble();
 
            this.velocity = ins.ReadDouble();
 
            this.velocity_east = ins.ReadDouble();
 
            this.velocity_north = ins.ReadDouble();
 
            this.velocity_up = ins.ReadDouble();
 
        }
 
        public sensor_msgs.SITLGps Copy()
        {
            sensor_msgs.SITLGps outobj = new sensor_msgs.SITLGps();
            outobj.time_usec = this.time_usec;
 
            outobj.latitude_deg = this.latitude_deg;
 
            outobj.longitude_deg = this.longitude_deg;
 
            outobj.altitude = this.altitude;
 
            outobj.eph = this.eph;
 
            outobj.epv = this.epv;
 
            outobj.velocity = this.velocity;
 
            outobj.velocity_east = this.velocity_east;
 
            outobj.velocity_north = this.velocity_north;
 
            outobj.velocity_up = this.velocity_up;
 
            return outobj;
        }
    }
}

